### ISSUE TITLE
subscribe API

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache-sdk-js#10]
In Dart we use `Stream<R>` which provides a pretty ergonomic API.

JS does of course not have anything like this. DOM has a `ReadbleStream` and Node has `Readable` stream.

See #9 for implementation using `ReadableStream`. There are some issues with `ReadbleStream`:

- ReadableStream only allows a single error. After the stream errors it
becomes unusable.
- The API is not as convenient as the Dart one. If using async iterator
it is nice but there is no imperative API around it.

Dying after an error seems like a blocker to me.

I'm tempted to use a much simpler API. Strawman:

```ts
type Subscription<Data extends JsonType> = {
  onData: (data: Data) => void;
  onError: (error: any) => void;
  close(): void;
};

subscribe(...) : Subscription {}
```

It would just call these methods over and over until the subscription is closed.

We could have this be an AsyncIterator too (it can be done in the future too) which would allow writing:

```ts
let sub = subscribe(...);
for await (const x of sub) {
  setState({x});
}
```

but it is not clear how error handling should be done here either.

**Comment by aboodman** [comment]
Three thoughts:

1/ We don't have to replicate the Dart API. It was convenient and very idiomatic to use Stream in Dart, we should do whatever the idiomatic thing is in each platform.

2/ What's the difference between the AsyncIterator and a Stream? They look the same to me.

3/ I don't understand the question of error handling with AsyncIterator. What happens, generally, when a generator function throws?

Maybe we should talk about this tomorrow in realtime and you can explain the issues and we can work through it.

**Comment by aboodman** [comment]
Four thoughts:

Totally fine with a simple API like you describe on which we layer more clever things in the future.

**Comment by arv** [comment]
1. Of course. I just wanted something as a first take. Streams are part of the platform, it is just that there are multiple platforms for JS.
2. AsyncIterator allows `for await` loops. `Stream` has more API surface but is usually also an async iterator.
3. When it throws the `for await` loop throws. In our case we want to continue the stream of data.

I will do (4). Keep it simple to start with. I will do that in a followup PR.

**Comment by aboodman** [comment]
> When it throws the for await loop throws. In our case we want to continue the stream of data.

Oh, bummer :(. That really sucks.

**Comment by aboodman** [comment]
Worth looking at what competitors do. Firestore (admittedly designed before async interators I bet), does (4):

https://firebase.google.com/docs/reference/js/firebase.firestore.Query#onsnapshot
