### ISSUE TITLE
Cannot easily switch to debug build of replicache

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-sdk-js#134]
You can change `wasmModule` to e.g., `./output/wasm/debug/replicache_client_bg.wasm`, but that doesn't change the version of the JS wrapper that is compiled, so you get compile errors.

These two actually need to change together so maybe we need a way to point to the directory that contains the two of them, not the wasm module at all?

**Comment by arv** [comment]
My plan is to have two different bundles; replicache and replicache-dev

**Comment by aboodman** [comment]
I guess that seems straightforward. Is that a common solution?

**Comment by arv** [comment]
Common enough. The other one is to use `process.env` and rely on bundlers to strip the dead code that it results from.
