### ISSUE TITLE
Expose more direct index API on Replicache class

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache-sdk-js#144]
Add convenience methods on Replicache class that both registers and invokes the "mutator" functions and maybe remove the methods on WriteTransaction?

Strawman:

```ts
class Replicache {
  ...
  createIndex(def: {name: string, keyPrefix?: string: jsonPointer: string}): Promise<void>;
  dropIndex(name: string): Promise<void>;
}
```

or

```ts
class Replicache {
  ...
  createIndex(...def: {name: string, keyPrefix?: string: jsonPointer: string}[]): Promise<void>;
  dropIndex(...name: string[]): Promise<void>;
}
```

**Comment by aboodman** [comment]
No strong opinion on the conveniences, but I think it's a feature that it's *possible* to define secondary indexes within a transaction. Many other systems I have worked on do not allow schema changes within transactions and it sssuuuuckks. Don't want to add Replicache to that list.
