### ISSUE TITLE
iloop spotted in Songbook Studio when mutator name not found

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-sdk-js#188]
See attached:

![2020-11-05](https://user-images.githubusercontent.com/80388/98316173-f9f6b480-1f7d-11eb-9309-fb85e13abe3d.png)

This error was happening in a tight loop, we were calling `maybeEndSync` thousands of times.

**Comment by arv** [comment]
Sounds similar to this old issue: https://github.com/rocicorp/replicache-sdk-flutter/commit/61a587bde6e45344de95232c671e230c54bde042#r38960411

I'm going to do retry counter...

**Comment by aboodman** [comment]
I agree that implementing a retry counter is a good idea, but this is a little different, and should be handled specially.

The case here is that repc is asking us to replay a mutation that the developer hasn't registered. I think we should detect this, print an error to console, and treat the mutation as a no-op.

**Comment by arv** [comment]
I see

**Comment by arv** [comment]
We do log it to the console. https://github.com/rocicorp/replicache-sdk-js/blob/92a9ae6a94be2926188ca55393164b40758addde/src/replicache.ts#L439-L443

I think the question is to how to get out of this loop.

**Comment by aboodman** [comment]
🙏

**Comment by aboodman** [comment]
This same iloop happens with a different error, time travel:

<img width="781" alt="Screen Shot 2020-11-14 at 12 50 43 AM" src="https://user-images.githubusercontent.com/80388/99145501-886cd500-2613-11eb-8bf8-70db9d456049.png">

This one mainly comes up during development, if the server state is nuked and clients still exist. We still shouldn't iloop.

**Comment by aboodman** [comment]
I'm not 100% sure if this is the same case or something different:

https://rocicorp.slack.com/archives/CMQQ9EDML/p1605452882064400

In the screenshot @elsigh provided I don't see the time travel message, but when I looked at it with him over VC I did. But he also had changed something by the time I looked. We should ensure that this never iloops for errors.

**Comment by aboodman** [comment]
I think we should only loop if there were no exceptions *and* there are still pending transactions. Maybe even in that case, we should only try a few times.

**Comment by arv** [comment]
Commit had wrong issue number in it

**Comment by arv** [comment]
It would be useful with more information here too.

Looking at the code it seems that the only way we are getting a `"beginSync"` loop is if we:
- need to reauth due to 401
- call `getDataLayerAuth()`:
  - which returns non `null`/`undefined`
  - and we call `"beginSync"` again with the new `dataLayerAuth` which is still wrong.

**Comment by aboodman** [comment]
On Mon, Nov 16, 2020 at 12:49 PM Erik Arvidsson <notifications@github.com>
wrote:

> It would be useful with more information here too.
>
> Looking at the code it seems that the only way we are getting a
> "beginSync" loop is if we:
>
>    - need to reauth due to 401
>    - call getDataLayerAuth():
>       - which returns non null/undefined
>       - and we call "beginSync" again with the new dataLayerAuth which is
>       still wrong.
>
> That's exactly what happened. There was a bug on the server that caused it
to not accept any auth.

In that case we should not loop.

**Comment by aboodman** [comment]
On Mon, Nov 16, 2020 at 12:50 PM Aaron Boodman <aaron@aaronboodman.com>
wrote:

>
>
> On Mon, Nov 16, 2020 at 12:49 PM Erik Arvidsson <notifications@github.com>
> wrote:
>
>> It would be useful with more information here too.
>>
>> Looking at the code it seems that the only way we are getting a
>> "beginSync" loop is if we:
>>
>>    - need to reauth due to 401
>>    - call getDataLayerAuth():
>>       - which returns non null/undefined
>>       - and we call "beginSync" again with the new dataLayerAuth which
>>       is still wrong.
>>
>> That's exactly what happened. There was a bug on the server that caused
> it to not accept any auth.
>
> In that case we should not loop.
>

Actually sorry - on second thought, I think that what happened was that
beginSync actually threw an exception, because it was seeing TimeTravel.
But yeah, sorry I don't have the details so we cannot know for sure.

But still what you describe there can certainly easily happen during
development, and we shouldn't loop.

**Comment by arv** [comment]
If `"beginSync"` throws an exception we do not iloop. It will try again after `syncInterval` ms. Does that fit with what you are seeing?

We could potentially back off the sync interval when syncing fails, but that would be a different bug.

**Comment by arv** [comment]
Closing for now. We fixed this underlying issue.

**Comment by aboodman** [comment]
Have we pushed a new version since then? I saw something like this in
Songbook Studio again last night, but I don't know if (a) we've pushed the
fix or (b) Lindsey has included it.

**Comment by arv** [comment]
Change is in v3.1.0

**Comment by elsigh** [comment]
I'm on 2.0.2 so I'll update now and deploy

**Comment by elsigh** [comment]
I updated locally, started my server and I'm seeing exceptions in the console and my app never initializes accordingly.
![image](https://user-images.githubusercontent.com/517210/102262493-0862b500-3ec8-11eb-8c8b-970bf7c01fe6.png)

**Comment by aboodman** [comment]
It looks like we had a breaking change in the internal data format somewhere along the lines. I can't remember when we decided to stop doing that, but it could have been the 2/3 boundary. Try starting it in a clean profile as an experiment :(.

**Comment by aboodman** [comment]
Also Erik's about to push 4.0 which has the fix for calling onData too
frequently.

**Comment by elsigh** [comment]
oh cool, I'm going to see where/how to catch the exception and try to log myself out programmatically (which wipes the db)
