### ISSUE TITLE
wasmModule load error if loaded from /foo/bar.html

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-sdk-js#206]
See: https://rocicorp.slack.com/archives/CMQQ9EDML/p1605450570063600, but the crux of it is that customer sees:

```
 CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
```

When instantiating Replicache from a path that contains multiple segments, like /foo/bar.html. It ends up trying to load /foo/replicache/....wasm in that case.

I'm not sure what's going on because the code looks correct to me.

Anyway, there are actually a few issues here:

- [ ] Correct the defaulting mechanism.
- [ ] replicache_client.js should not try and load at all if the response is 404. Can we easily put up a better error in that case?

**Comment by arv** [comment]
I wonder if the dealing of 404 is only an issue when the server does not send the correct MIME type?

```js
if (module.headers.get('Content-Type') != 'application/wasm') {
    console.warn("`WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:\n", e);
```

and if the MIME is incorrect it does the following:

```js
const bytes = await module.arrayBuffer();
return await WebAssembly.instantiate(bytes, imports);
```

with checking the HTTP status  code.

**Comment by arv** [comment]
> replicache_client.js should not try and load at all if the response is 404. Can we easily put up a better error in that case?

I think we could catch the exception and do an HTTP head if we really wanted.

**Comment by arv** [comment]
I'm having a hard time reproing this.

Can I haz moar info?
 - Is this with Next.js (I assume it is given the implicit background info)
 - Is this with `wasmModule` passed in to `Replicache`?
   - If so, what value is being used?
   - Where is the wasm file located? If `wasmModule` is used the wasm file location is managed by the user of the Replicache API.

**Comment by elsigh** [comment]
Yes to Next.js and I bet it's the relative bit of this: `wasmModule: "replicache/wasm/release/replicache_client_bg.wasm",` I could just use `/replicache` since we have a symlink there in my `public` dir. I'll try that real quick

**Comment by elsigh** [comment]
Doh, that fixed it. so maybe it was just working as written.

**Comment by arv** [comment]
If you pass in `wasmModule` it might make sense to use `new URL(relativePathFromCurrentFile, import.meta.url)`

> Doh, that fixed it. so maybe it was just working as written.

I'll add some more JSDocs for `wasmModule`.

**Comment by aboodman** [comment]
Doh. My fault for not thinking of this.

Erik has recently improved the nextjs support so passing this value in is
no longer necessary at all. We default it to the correct thing.

You have to make a minor change to your webpack config and upgrade to
latest Replicache. See:

https://github.com/rocicorp/replicache-sdk-js/commit/95d63ffbaac567aa4524de1ae481065b8b1a78b5#diff-679231efd4c66b143f24431fa009f76ece3270fbb190521cb71403ed88227030

for details.

**Comment by arv** [comment]
Fixed in https://github.com/rocicorp/replicache-sdk-js/commit/b054d40198b0d53d785f77c6229dd2ade2e58d31
