### ISSUE TITLE
populate performance degraded by 20%

### ISSUE THREAD

**Issue by phritz** [rocicorp/replicache-sdk-js#218]
(broken off from https://github.com/rocicorp/replicache-sdk-js/issues/216)

aaron says:
> OK so @phritz https://github.com/rocicorp/repc/releases/tag/v0.13.0  caused a ~20% reduction in populate perf. 
> ...
> See graphs here: https://replicache-sdk-js-perf-git-perf-data.rocicorp.vercel.app/ and corresponding code here: https://github.com/rocicorp/replicache-sdk-js/blob/master/perf/perf.js#L224
perf/perf.js:224

I went through each commit looking for culprits and this is what I found. My guess is it's this first issue that is causing it:
  - nulls in strings! presumably this text decoder will happily include 0 bytes in strings, as it should: https://github.com/rocicorp/replicache-sdk-js/blob/a1c6693acd6c4bfc7c4505f6f14ce69e378b2525/perf/perf.js#L16. However we disallow nulls in values that we index so it will trigger an info log and not actually be indexed: https://github.com/rocicorp/repc/blob/111ac9d65f95063585a0d804e07866489ec6c171/src/db/write.rs#L238. we also allocate a string in this case: https://github.com/rocicorp/repc/blob/111ac9d65f95063585a0d804e07866489ec6c171/src/db/write.rs#L242 and actually another one deeper down in get_index_keys
  - in change to enable indexing of arrays of strings, when indexing a value for clarity of code we allocate two vectors where previously allocated one: https://github.com/rocicorp/repc/commit/d236be1cfaad55c0503f6096e682e30a9150df71#diff-de56dc115857f21293cddf89faae00fe8e3ea912edc415f23f1460a0759412c4R153
  - we now allocate a log context in put(): https://github.com/rocicorp/repc/commit/d236be1cfaad55c0503f6096e682e30a9150df71#diff-12bae3eeae5df2dd1462fc0318ea11233efb4360f197e65551f0885dd7fd25dfR134
  - we encode our own index key instead of using bytekey, but we do this in the maximally efficient way (reserving enough space up front) so i do not think this is an issue, but mentioning for completeness: https://github.com/rocicorp/repc/commit/19a16986817e8fcbd5b1fbbcf80aaa26d5327677#diff-de56dc115857f21293cddf89faae00fe8e3ea912edc415f23f1460a0759412c4R186

btw careful inferring anything from https://github.com/rocicorp/repc/commit/74db97cabedabb8ae9e6de81c62373b26a8bf474 because there were inefficiencies introduced there eg allocating owned indexkeys instead of using &[]s that were fixed in later commits.

---

@aboodman / @arv : I think we should fix the first issue which is an issue with the test itself by changing any 0 bytes in the random strings to something else like a 1 byte and re-running. my guess is the performance "change" will go away. i think we only look at the other things if that doesn't fix the "problem".

**Comment by aboodman** [comment]
Wow, interesting! 

One thing I've learned from having these benchmarks is that at least half the work is making the tests themselves high quality.

Sure @arv you want to change to not include null bytes?

**Comment by arv** [comment]
I don't think it is the NULL bytes in strings since we are JSON.stringify these.

```js
JSON.stringify(String.fromCodePoint(0))
`"\\u0000"`
```

But running the tests too.

**Comment by arv** [comment]
Removing \0 seems to have fixed that.

All the other perf improvements are going to be hard to see without a dedicated machine.
