### ISSUE TITLE
Polish changes to constructor API

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-sdk-js#263]
It would be cool if we could omit `batchURL`, `diffServerURL`, and `clientViewURL` and if omitted, those functions just won't work. Like if you don't specify a `batchURL` we won't push. And if you don't specify a `diffServerURL` and `clientViewURL`, then we won't pull.

This would make getting started a bit easier because I think people tend to play with the JS API before digging into server side integration.

**Comment by arv** [comment]
I like this in general.

Let's assume we make `clientViewURL` optional. Right now we go all the way to the diff-server which then returns an error. I assume we should instead catch this case in repc and log using `console.info` and skip the pull.

If we want to do this I suggest we do this now before we make another major release version.

**Comment by aboodman** [comment]
I'm not 100% on the changes that @phritz has recently added. Is there a default clientViewURL that is set server side or is it always required for client to provide one.

If the latter, then your proposal makes sense. If app developer doesn't provide both diffServerURL and clientViewURL then repc just skips the pull and prints out a log.

**Comment by arv** [comment]
> I'm not 100% on the changes that @phritz has recently added. Is there a default clientViewURL that is set server side or is it always required for client to provide one.

diff-server supports v2 (without a client view URL) and v3 (client view URL is required) but repc forces us into v3 now.

**Comment by aboodman** [comment]
This has been implemented (yay).
