### ISSUE TITLE
API Polish: It would be nice to have a one-liner if a scan is empty

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-sdk-js#264]
Right now I think the easiest way to express it is:

```
const empty = await this.rep.scan().keys().next().done;
```

**Comment by arv** [comment]
@elsigh Wanted this too. I was considering adding `isEmpty()` or `get size()`. I would prefer to not add both and size is probably the more powerful.

`size` would need a new RPC to be efficient but it might be worth it.

**Comment by aboodman** [comment]
I think in order to calculate `size()` you have to do extra work in the rust layer too, particularly anticipating a future with prolly trees. Also if what you want to know is if the result is non-empty, which is common, typing `empty()` is easier than `size() != 0` or `Boolean(size())` or whatever.

So why not have both?

**Comment by arv** [comment]
> So why not have both?

Just to reduce API surface.

**Comment by aboodman** [comment]
I vote have both, but 🤷‍♂️. One of the two would be great.
