### ISSUE TITLE
clientViewURL should accept relative URLs

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-sdk-js#273]
This will probably just fix itself when we remove the diff server, but if I do:

```
const rep = new Replicache({
  clientViewURL: '/api/replicache-client-view',
  ...
}
```

I get the following output from local diff server:

```
11 Feb 21 03:15:56.000 -1000 INF got error fetching clientview: error sending client view http request: Post "/api/replicache-client-view": unsupported protocol scheme "" gr=265 req=/pull rid=78 syncID=ff302e22-353e-4402-a3a9-add115965209-cd69bf2d-7
```

Replicache is passing the clientViewURL value straight through without resolving it, then diff server is sad.

**Comment by aboodman** [comment]
Even if there's nothing to do here because ds is going away, let's leave this open so we remember to test that it's fixed later.

**Comment by arv** [comment]
This is so easy I'm just going to deal with these
