### ISSUE TITLE
Flag to make Replicache in-memory only

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-sdk-js#276]
This would make developing multiusers apps much easier until we have in-memory caching built-in to the persistent version of Replicache.

**Comment by arv** [comment]
I'm vary to make this change until we have a solid design for how to make in-memory caching work.

**Comment by phritz** [comment]
My spidey senses are tingling at the blithe way we are talking about doing away with a fundamental assumption in the system (persistence). For a

**Comment by phritz** [comment]
My spidey senses are tingling at the blithe way we are talking about doing away with a fundamental assumption in the system (persistence). I'm not saying we shouldn't, I'm saying we shouldn't treat it as lightly as we are.  There are probably a lot of hidden gotchas we are not thinking about given how deep the persistence assumption is baked. https://github.com/rocicorp/replicache-sdk-js/issues/275 is a good example of this. Was also wondering what the effect on indexes would be. Using memstore for a demo seems fine but we shouldn't fool ourselves into thinking we can just switch to memstore without treating it like an engineering question and expect everything to work out fine. Memstore was intended for tests and everything we have done assumes persistence; if we want to consider making this switch for real, we need to do it like engineers...
