### ISSUE TITLE
Make push fasterer

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-sdk-js#286]
Right now, we wait for a silence of `pushDelay` before sending pushes to the server.

Experience shows this doesn't make sense - we want to bias toward liveness.

Instead we should push as rapidly as connection limits will allow us, even overlapping pushes if necessary due to server responsiveness. Remember that in Replicache, we don't care about the response to a push.

===

Looking briefly, it's unclear to me if HTTP/2 support means there's no limit to number of allows http requests (for supporting servers) and if we can detect this.

Something to investigate.

**Comment by arv** [comment]
Do we really want to push the same commits multiple times at the same time? It is safe but a little bit wasteful.

**Comment by aboodman** [comment]
I guess this was phrased a little aggressively. Heh.

At the very least we don’t want to wait for any quiescence at all. PushDelay should go away. Perhaps that should be a separate commit.

As for sending duplicate mutations. We already do this commonly and will under normal circumstances as we target more real time performance, because of the way push and pull are decoupled.

I think it is ok. The only waste is network overhead and (de)serialization. The server just skips every mutation it’s already seen, and it doesn’t cost any extra to do that check as it’s an integer compare of lastMutationID.

**Comment by aboodman** [comment]
I'm going to open a different bug starting from the problem.
