### ISSUE TITLE
Client waits until writes pause to send push

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-sdk-js#287]
Currently, the way `pushDelay` is used, we wait until writes stop to send a push. This does not work for multiuser applications, because for things such as drag/drop we want to propagate changes as the user is moving the mouse.

I think a `pushDelay` still makes sense but (1) the default should be a lot shorter, like maybe 5-10ms? and (2) it shouldn't wait for quiescence, it should just fire push once it's been `pushDelay` since the first write.

**Comment by phritz** [comment]
We recently changed assumptions from one sync at a time to overlapping pushes and maybe pulls. I'm not sure there are any consequences we should be thinking about, but wrt this specific change:
- does a *replay* mutation trigger a push? Hopefully not.
- does whatever code we have to re-auth work well in the face of overlapping pushes? Previously the app would get a 401 or whatever; now it will potentially get a *flood* of them when auth is busted.

**Comment by aboodman** [comment]
These are good questions but maybe wrong bug? #288

**Comment by phritz** [comment]
The second one belongs there but seems like the first one (don't trigger push on replay mutation) might be relevant here. There is going to be / is triggering and debounce logic somewhere that needs to know the difference between the two otherwise we potentially trigger a lot of useless pushes. I will add it there too.

**Comment by aboodman** [comment]
> does a replay mutation trigger a push? Hopefully not.

yeah i was being loose with my terminology here. syncs are currently (in current checked in code) triggered:

1. on mutations, but delayed until `pushDelay` of quiescence
1. on a timer, if `syncIterval` is non-zero
1. manually, when user calls `sync()`

This big is just about removing the quiescence aspect of the first one.

**Comment by aboodman** [comment]
It seems like this is fixed now @arv ?

**Comment by arv** [comment]
It is on the arv/begin-pull-push branch
