### ISSUE TITLE
Consider sending overlapping pushes

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-sdk-js#288]
Even after #287 is done, we will still be limited in the rate we can push updates between clients by the latency to the data layer.

For example, if the latency to a server is 100ms, then we can push updates no faster than 10/s.

We should consider allowing a limited amount of overlapping push requests. One charm about how push and pull are separated in the Replicache protocol is that it's fine to send pushes that have mutations that were sent in a previous mutation. The server just ignores those.

**Comment by phritz** [comment]
- we should ensure that replaying a mutation doesn't trigger a push
- we should ensure that re-auth works well in the face of overlapping pushes. Previously the app would get a 401 or whatever; now it will potentially get a flood of them when auth is busted.

**Comment by aboodman** [comment]
Yeah there are a lot of assumptions that will probably be jostled by this. Another is ... offline. You don't want to pile up a zillion requests when you're offline, obvs.

This one would require a design sketch for sure.

**Comment by aboodman** [comment]
Closing this for now since we don't intend to do it in near future.

Note for future self: we discovered one challenging issue here: there are no semantics for `cookie`. So if we receive pull responses out of order, the client could see time go backwards. It seems like if we want to do this we'd have to force pull responses to be orderable 😬
