### ISSUE TITLE
Scan is difficult to use

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-sdk-js#30]
It's pretty hard to use right now. This is my fault, I just threw it together because it wasn't the most important thing at the time. Some things that stand out right away:

* Users shouldn't have to batch the calls themselves. They should get a cursor thingy that intelligently pages in results behind the scenes ahead of them. The way we have it now is both hard to use *and* slow.
* There should be the ability to scan in reverse.
* Further out, we should consider adding some kind of basic filtering that can be implemented in the client so useless results don't have to be returned up to JS. This is a big one, but I'm hopeful that there's some library we can take off the shelf. There's no value in Replicache having its own filter syntax.

**Comment by aboodman** [comment]
It seems like it would be possible to implement the better cursor on top of what we have right now, without changing the repm API at all (yay transactions!), and that's probably desirable.

**Comment by arv** [comment]
Let me make sure I understand.

- We should remove `limit` and just use an iterator that moves forward as needed.
- We might still want a way to set `start` but we should also have a way to move the cursor forwards and backwards.
- With reverse we need to know how many items there are if we want to start at the end. This seems like it requires a change to repm API.

**Comment by aboodman** [comment]
Yeah I think maybe this should be three chunks of work.

# First chunk: iterator.

> We should remove limit and just use an iterator that moves forward as needed.

Right, and importantly, my idea is that the iterator should attempt to preload the next chunk of data ahead of the caller getting to end of currently loaded data, to hide latency of fetching chunks. The iterator would still have to be async of course in ES6 because we can't guarantee we have the data ready, but we'd try to set things up so that it almost always will be. Can you comment on what the performance overhead of async iteration is here, compared to a non-async version where you always have the data on the UI thread?

> We might still want a way to set start

The mechanisms we have to set scan bounds should be retained --

* scan a certain prefix
* start at a certain offset
* start at a certain key

# Second chunk: reverse iteration

> we should also have a way to move the cursor forwards and backwards.

# Third chunk (far future): filtering

I think we should resist adding filtering until we have pushed https://github.com/rocicorp/replicache-client/issues/107 as far as we think we can. The API can be far less complex to Replicache if we can just make scan blindingly fast.

**Comment by arv** [comment]
The overhead of async iteration vs non async is that every step is a microtask, which means the callstack unwinds.

**Comment by aboodman** [comment]
But I mean ... does it make it slower? Maybe we'll have to measure it.

**Comment by arv** [comment]
Slower? Yes. Noticeably so? My gut answer is no but we should measure it.

**Comment by arv** [comment]
Another thing to keep in mind is that React is not very good with async so React apps are probably just going to wait for all the data to get there.

**Comment by aboodman** [comment]
Well I'm imagining that this is all going to be wrapped in a `subscribe()` or `query()` anyway. So it's not going to really allow data to stream into the UI or anything - that's not the point. The point is to prevent developer from having to write the nested iteration logic or worry about how big to make the chunks.

**Comment by arv** [comment]
The async iterator escapes your `query` or `subscribe` if they return the return value of a `scan`. See #36

**Comment by aboodman** [comment]
@arv I think this is done now? closing. re-open if wrong.
