### ISSUE TITLE
Mutate functions API

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache-sdk-js#35]
The initial plan was for `register` to take a function with var args and return a function that strips the `tx` param. Something along the lines of:

```ts
const setTodoText = rep.register(
  async (tx: WriteTransaction, id: Id, text: string): Promise<void> {

  });

...

setTodoText(42, 'Hello');
```

This design was discarded because limitations in Dart (no var args) so we ended up with:

```ts
const setTodoText = rep.register(
  async (tx: WriteTransaction, {id, text}: id: Id, text: string): Promise<void> {

  });

...

setTodoText({id: 42, text: 'Hello'});
```

...where we have a single `arg` that can be any JSON value.

It is not a big deal because the developer can easily wrap this as needed:

```ts
const setTodoTextInner = rep.register(
  async (tx: WriteTransaction, {id, text}: id: Id, text: string): Promise<void> {

  });

const setTodoText = (id: Id, text: string) => setTodoTextInner({id, text});

...

setTodoText(42, 'Hello');
```

## The problem

We need to store the arguments in the write transaction so that we can replay the transaction later. And we need to store these arguments in a language agnostic way.

## Possible Solutions

To allow flexibility between the language bindings we need to either:

- Force Dart to use a Dart `List` as the arg
- Allow JS to rewrite the `Array` to a `Map` as needed.

## Suggested Path Forward

**Do nothing.**

It is not a big deal and with TypeScript the type info/autocomplete makes working with object as maps less painful.

**Comment by arv** [comment]
FYI @aboodman

**Comment by aboodman** [comment]
The other thing is that on the server-side, it's more natural/common to just have the single object param, which is called the request payload in that context.

Let's stick with this for awhile and see how it feels.
