### ISSUE TITLE
Pending local state lost on refresh of containing web page 😑

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache-sdk-js#40]
You can replicate the bug like this:

- Use one of the JS sample apps
- Make an edit
- Before sync happens, refresh the page
- The pending change is lost

This is because we're assigning a new client ID at startup in the replicache-client, so we get a new local DB on each startup.

It seems like the client ID needs to be stored somewhere. How did we do it in Flutter?

**Comment by arv** [comment]
The `ClientID` is created as needed when we `Dispatch` `"open"` so it is all inside replicache-client. I don't see how this is different in Dart vs JS.

**Comment by arv** [comment]
We are getting a new `storageDir` every time we start the `test_server`. For Dart this was passed into `Init` from Java/ObjC.

For `test_server` I think it is the right thing to always reset this, but for `test_server` as a temporary work around until we have Wasm we should have a stable `storageDir`. I'm adding a command line flag.

**Comment by arv** [comment]
Next step is:
- do another release
- roll the build deps
- Update readme

**Comment by aboodman** [comment]
All done.
